version: '2'
services:
    web:
         image: zlp11313.vci.att.com:5100/com.att.dev.argos/centos7-python3-mod_wsgi:$TAG
         container_name: hello_mod_wsgi_dev
         ports:
             - "8001:8001"
         logging:
             driver: json-file
             options:
                 max-size: "5m"
