version: '2'
services:
    web:
         image: dockercentral.it.att.com:5100/com.att.dev.argos/centos7-python3-mod_wsgi:3.6.6
         container_name: hello_mod_wsgi
         ports:
             - "8001:8001"
         logging:
             driver: json-file
             options:
                 max-size: "5m"
